### ISSUE TITLE
Broken link to bga-carcassonne-scripts

### ISSUE THREAD

**Issue by DavidEGx** [yzemaze/bga-scripts#1]
The link in the readme towards https://github.com/yzemaze/bga-carcassonne-scripts is broken. Maybe the repository is not public?

Thanks for the work!

**Comment by yzemaze** [comment]
Yep, I’ve deliberately set it to private after CraftyRaf’s tip in the Carcassonne WhatsApp group last Saturday. It was a bit premature as I didn’t want the Carcassonne scripts to be widely available before contacting the WTCOC-/DAZ-Team. I’m still waiting for a response regarding rules compliance of (some of) them.

**Comment by yzemaze** [comment]
Carcassonne repo is set to public again.
